---
# -------------------------------------------------------------------------#
# 1. 冪等性を担保するために.gitがあるかを確認する
# -------------------------------------------------------------------------#
- name: Check File .git
  stat:
    path: /var/www/raisetech-live8-sample-app/.git
  register: git

# -------------------------------------------------------------------------#
# 2. .gitがある = Clone されている。最新であることの保証がないため、一旦削除する
# -------------------------------------------------------------------------#
- name: Git Clone Delete
  become: yes
  shell: bash -lc "{{ item }}"
  with_items:
    - sudo rm -rf raisetech-live8-sample-app
  args:
    chdir: /var/www
  when: git.stat.exists

# -------------------------------------------------------------------------#
# 3. Clone = 最新のアプリケーションを取得
# -------------------------------------------------------------------------#
- name: Git clone rails-app
  git:
    repo: https://github.com/aoha968/raisetech-live8-sample-app.git
    dest: /var/www/raisetech-live8-sample-app

# -------------------------------------------------------------------------#
# 4. ディレクトリ、ファイルの所有者を変更(Read/Write/Execute権限を持たせる)
# -------------------------------------------------------------------------#
- name: Change Ownership
  become: yes
  shell: bash -lc "sudo chown -hR ec2-user /var"

# -------------------------------------------------------------------------#
# 5. Rails Setup (Gem/Bundle Install)
# -------------------------------------------------------------------------#
- name: Rails Setup
  become: yes
  shell: bash -lc "{{ item }}"
  with_items:
    - gem install bundler:2.3.14
    - bundle install
  args:
    chdir: /var/www/raisetech-live8-sample-app

# -------------------------------------------------------------------------#
# 6. Other Setttings
# -------------------------------------------------------------------------#
- name: Other Settings
  shell: bash -lc "{{ item }}"
  with_items:
    - rails db:create
    - rails db:migrate
    - yes | rails webpacker:install
    - rails webpacker:compile
    - bundle exec unicorn_rails -c config/unicorn.rb -D
    - sudo systemctl start nginx.service
  args:
    chdir: /var/www/raisetech-live8-sample-app
